/*
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include "Stm32F407xx.h"
#include "stm32f407xx_gpio_driver.h"

int main()
{

	GPIO_Handle_t GpioLED;

//	For Green LED

	GpioLED.pGPIOx=GPIOD;
	GpioLED.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_12;
	GpioLED.GPIO_PinConfig.GPIO_PinMode= GPIO_MODE_OUT;
	GpioLED.GPIO_PinConfig.GPIO_PinSpeed= GPIO_SPEED_FAST;
	GpioLED.GPIO_PinConfig.GPIO_PinOpType= GPIO_OP_TYPE_PP;
	GpioLED.GPIO_PinConfig.GPIO_PinPuPdControl= GPIO_NO_PUPD;

	GPIO_Init(&GpioLED);



    /* Loop forever */
	for(;;)
	{


		GPIO_ToggleOutputPin(GPIOD,GPIO_PIN_NO_12);//Toggle Green LED



		for(uint32_t i=0;i<1000000;i++);// for Delay.

	}

	return 0;
}


